name: build-and-release
run-name: Build and release ${{ github.event.release.tag_name }}
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  npm-install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build-python
      - name: Extract Version
        shell: bash
        run: echo VERSION=`cat package.json | jq -r '.version'` >> $GITHUB_OUTPUT
        id: version
      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "build/vastsdk-python-${{ steps.version.outputs.VERSION }}.tgz"
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }} 